# Generated by Django 4.2.1 on 2023-05-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
    ]
