# Generated by Django 4.2.1 on 2023-06-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_discordadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ['month']},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['channel_name']},
        ),
        migrations.AlterModelOptions(
            name='discordadmin',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='birthday',
            name='discord_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
